AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sqs-queue-chainer

  Sample SAM Template for sqs-queue-chainer

Globals:
  Function:
    Timeout: 3
Resources:
  AppSqsQueue:
    Type: AWS::SQS::Queue
  SenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sender/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt AppSqsQueue.Arn
            BatchSize: 10
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

Outputs:
  SenderFunction:
    Description: SenderFunction function name
    Value: !Ref SenderFunction

  SQSqueueName:
    Description: SNS queue name
    Value: !GetAtt AppSqsQueue.QueueName

  SQSqueueARN:
    Description: SQS queue ARN
    Value: !GetAtt AppSqsQueue.Arn

  SQSqueueURL:
    Description: SQS queue URL
    Value: !Ref AppSqsQueue
